#!/usr/bin/env ruby

require 'date'
require 'yaml'

BASE_DIR='/srv/www/cam/0'
RL_SNAP_CMD=File.expand_path(__dir__).chomp('/commander') + '/bin/rl-snap.sh'

config = YAML.load(File.read(File.dirname($0) + '/config.yaml'))

today = Date.today.to_s
now = Time.now.strftime('%H-%M')
img_file_name = "#{today}-#{now}.jpg"
img_file_path = "#{BASE_DIR}/#{img_file_name}"
system("#{RL_SNAP_CMD} #{img_file_path}")

# webdav upload
wd_config = config['upload']['webdav']
wd_cmd = "curl --user #{wd_config['user']}:#{wd_config['password']} -T #{img_file_path} #{wd_config['url']}/#{img_file_name}"
%x[#{wd_cmd}]
